name = "nice-ape-worker-dev"
main = "worker/index.ts"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket Configuration for Development
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "niceape-dev"
preview_bucket_name = "niceape-dev"

# D1 Database Configuration for Development (uses remote DB)
[[d1_databases]]
binding = "DB"
database_name = "nice-ape-dev"
database_id = "72bd529e-2054-4c2c-9f77-92ca5134de8e"
migrations_dir = "worker/db/migrations"
preview_database_id = "72bd529e-2054-4c2c-9f77-92ca5134de8e"

# Environment variables for Development
[vars]
ENVIRONMENT = "development"

# For production environment
[env.production]
name = "nice-ape-worker-prod"
[env.production.vars]
ENVIRONMENT = "production"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "niceape"

[[env.production.d1_databases]]
binding = "DB"
database_name = "nice-ape-prod"
database_id = "your-prod-database-id-here"
migrations_dir = "worker/db/migrations"
preview_database_id = "your-prod-database-id-here"